project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  [
    {
      source: src/modules/i18n/translations/en.json,
      translation: src/modules/i18n/translations/%two_letters_code%.json,
    },
  ]
