name: "🐛 UI Bug Report"
description: "Report a visual bug or issue in Music"
labels:
  - "Bug: UI"
  - "needs review"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file an UI bug report! Please fill out this entire form. The most important piece of information are screenshots/videos/actions that led to the bug.
  - type: input
    attributes:
      label: What device did this occur on?
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Android is your device running?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Have you modified your device's display or font size?
      multiple: false
      options:
        - "Yes"
        - "No"
        - I don't know
      description: |
        This helps determine if the issue stems from the user modifying the system UI.
        Essentially, see if you ever modified a value in: `Settings > Display > Display size and text`.
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: |
        List the app version you are currently using. This can be found in:
          - The "Settings" page in the app.
          - In the "App Info" page for Music on your device (`Settings > Apps > Music` then scroll down).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: |
        Clearly describe the problem or steps that led to this problem. Include any screenshots or videos showing this UI issue.
    validations:
      required: true
